language: python
python:
- '2.7'
before_install: npm install -g grunt-cli
install: 
- cd static
- npm install
- cd ..
- pip install -r requirements/local.txt
before_script: 
- cd static
- grunt
- cd ..
env:
- SECRET_KEY="shhthisisasecret" MANDRILL_KEY="notreallyneeded" MIXPANEL_KEY="alsonotneeded"
script: coverage run --source='comics,pebbles,profiles,saltpeter,nest' --omit='*migrations*,*tests*,*settings*,*urls*,*wsgi*' manage.py test comics pebbles profiles saltpeter nest --settings=nest.settings.base && coverage report
notifications:
  email: false
  slack: inkpebble:E4ZgOJD6kJyY8JTl0Rrnyhno
deploy:
  provider: heroku
  api_key:
    secure: KPdJ2AcC5JZYhV+RnqUIzUhYtAoD2I5oXAfm3j0dzifPCzkgF1eBevjVGDfwwj80f6qWSsxBgMeniMsUqWEUTkryM99ifsHS5LlXCzZ9nWkjK1gfFW+3h+X6bog2RkAOp60sdsZmyIiasfFiVo72vuIlDG3km3WO53jMWnrnpD8=
  app: qc-stage
  strategy: git
  on:
    repo: ImmaculateObsession/nest
